# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  # panda_joint1: 0.0
  # panda_joint2: -0.785
  # panda_joint3: 0.0
  # panda_joint4: -2.356
  # panda_joint5: 0.0
  # panda_joint6: 1.571
  # panda_joint7: 2.845087

  panda_joint1: 1.84501
  panda_joint2: 0.382177
  panda_joint3: 0.382656
  panda_joint4: -1.10875
  panda_joint5: -0.229628
  panda_joint6: 1.5618
  panda_joint7: 0.584073
